#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexna.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Alexna")]
	public partial class alexnaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertFestivos(Festivos instance);
    partial void UpdateFestivos(Festivos instance);
    partial void DeleteFestivos(Festivos instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertCursos(Cursos instance);
    partial void UpdateCursos(Cursos instance);
    partial void DeleteCursos(Cursos instance);
    partial void InsertAsignaturas(Asignaturas instance);
    partial void UpdateAsignaturas(Asignaturas instance);
    partial void DeleteAsignaturas(Asignaturas instance);
    #endregion
		
		public alexnaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AlexnaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Festivos> Festivos
		{
			get
			{
				return this.GetTable<Festivos>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Cursos> Cursos
		{
			get
			{
				return this.GetTable<Cursos>();
			}
		}
		
		public System.Data.Linq.Table<Asignaturas> Asignaturas
		{
			get
			{
				return this.GetTable<Asignaturas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Festivos")]
	public partial class Festivos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Festivo_Fecha;
		
		private string _Festivo_Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFestivo_FechaChanging(System.DateTime value);
    partial void OnFestivo_FechaChanged();
    partial void OnFestivo_DescripcionChanging(string value);
    partial void OnFestivo_DescripcionChanged();
    #endregion
		
		public Festivos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Festivo_Fecha", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Festivo_Fecha
		{
			get
			{
				return this._Festivo_Fecha;
			}
			set
			{
				if ((this._Festivo_Fecha != value))
				{
					this.OnFestivo_FechaChanging(value);
					this.SendPropertyChanging();
					this._Festivo_Fecha = value;
					this.SendPropertyChanged("Festivo_Fecha");
					this.OnFestivo_FechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Festivo_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Festivo_Descripcion
		{
			get
			{
				return this._Festivo_Descripcion;
			}
			set
			{
				if ((this._Festivo_Descripcion != value))
				{
					this.OnFestivo_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._Festivo_Descripcion = value;
					this.SendPropertyChanged("Festivo_Descripcion");
					this.OnFestivo_DescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _usuario;
		
		private string _password;
		
		private bool _administrador;
		
		private bool _profesor;
		
		private bool _alumno;
		
		private bool _mantenimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnadministradorChanging(bool value);
    partial void OnadministradorChanged();
    partial void OnprofesorChanging(bool value);
    partial void OnprofesorChanged();
    partial void OnalumnoChanging(bool value);
    partial void OnalumnoChanged();
    partial void OnmantenimientoChanging(bool value);
    partial void OnmantenimientoChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_administrador", DbType="Bit NOT NULL")]
		public bool administrador
		{
			get
			{
				return this._administrador;
			}
			set
			{
				if ((this._administrador != value))
				{
					this.OnadministradorChanging(value);
					this.SendPropertyChanging();
					this._administrador = value;
					this.SendPropertyChanged("administrador");
					this.OnadministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profesor", DbType="Bit NOT NULL")]
		public bool profesor
		{
			get
			{
				return this._profesor;
			}
			set
			{
				if ((this._profesor != value))
				{
					this.OnprofesorChanging(value);
					this.SendPropertyChanging();
					this._profesor = value;
					this.SendPropertyChanged("profesor");
					this.OnprofesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno", DbType="Bit NOT NULL")]
		public bool alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				if ((this._alumno != value))
				{
					this.OnalumnoChanging(value);
					this.SendPropertyChanging();
					this._alumno = value;
					this.SendPropertyChanged("alumno");
					this.OnalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mantenimiento", DbType="Bit NOT NULL")]
		public bool mantenimiento
		{
			get
			{
				return this._mantenimiento;
			}
			set
			{
				if ((this._mantenimiento != value))
				{
					this.OnmantenimientoChanging(value);
					this.SendPropertyChanging();
					this._mantenimiento = value;
					this.SendPropertyChanged("mantenimiento");
					this.OnmantenimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cursos")]
	public partial class Cursos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Curso_Id;
		
		private string _Curso_Nombre;
		
		private bool _Curso_Activo;
		
		private System.DateTime _Curso_Fecha_Inicio;
		
		private System.DateTime _Curso_Fecha_Fin;
		
		private string _Curso_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCurso_IdChanging(int value);
    partial void OnCurso_IdChanged();
    partial void OnCurso_NombreChanging(string value);
    partial void OnCurso_NombreChanged();
    partial void OnCurso_ActivoChanging(bool value);
    partial void OnCurso_ActivoChanged();
    partial void OnCurso_Fecha_InicioChanging(System.DateTime value);
    partial void OnCurso_Fecha_InicioChanged();
    partial void OnCurso_Fecha_FinChanging(System.DateTime value);
    partial void OnCurso_Fecha_FinChanged();
    partial void OnCurso_ObservacionesChanging(string value);
    partial void OnCurso_ObservacionesChanged();
    #endregion
		
		public Cursos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Curso_Id
		{
			get
			{
				return this._Curso_Id;
			}
			set
			{
				if ((this._Curso_Id != value))
				{
					this.OnCurso_IdChanging(value);
					this.SendPropertyChanging();
					this._Curso_Id = value;
					this.SendPropertyChanged("Curso_Id");
					this.OnCurso_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Nombre", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string Curso_Nombre
		{
			get
			{
				return this._Curso_Nombre;
			}
			set
			{
				if ((this._Curso_Nombre != value))
				{
					this.OnCurso_NombreChanging(value);
					this.SendPropertyChanging();
					this._Curso_Nombre = value;
					this.SendPropertyChanged("Curso_Nombre");
					this.OnCurso_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Activo", DbType="Bit NOT NULL")]
		public bool Curso_Activo
		{
			get
			{
				return this._Curso_Activo;
			}
			set
			{
				if ((this._Curso_Activo != value))
				{
					this.OnCurso_ActivoChanging(value);
					this.SendPropertyChanging();
					this._Curso_Activo = value;
					this.SendPropertyChanged("Curso_Activo");
					this.OnCurso_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Fecha_Inicio", DbType="Date NOT NULL")]
		public System.DateTime Curso_Fecha_Inicio
		{
			get
			{
				return this._Curso_Fecha_Inicio;
			}
			set
			{
				if ((this._Curso_Fecha_Inicio != value))
				{
					this.OnCurso_Fecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Curso_Fecha_Inicio = value;
					this.SendPropertyChanged("Curso_Fecha_Inicio");
					this.OnCurso_Fecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Fecha_Fin", DbType="Date NOT NULL")]
		public System.DateTime Curso_Fecha_Fin
		{
			get
			{
				return this._Curso_Fecha_Fin;
			}
			set
			{
				if ((this._Curso_Fecha_Fin != value))
				{
					this.OnCurso_Fecha_FinChanging(value);
					this.SendPropertyChanging();
					this._Curso_Fecha_Fin = value;
					this.SendPropertyChanged("Curso_Fecha_Fin");
					this.OnCurso_Fecha_FinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Curso_Observaciones
		{
			get
			{
				return this._Curso_Observaciones;
			}
			set
			{
				if ((this._Curso_Observaciones != value))
				{
					this.OnCurso_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Curso_Observaciones = value;
					this.SendPropertyChanged("Curso_Observaciones");
					this.OnCurso_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asignaturas")]
	public partial class Asignaturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Asignatura_Id;
		
		private string _Asignatura_Nombre;
		
		private System.DateTime _Asignatura_Fecha_Inicio;
		
		private System.Nullable<System.DateTime> _Asignatura_Fecha_Fin;
		
		private bool _Asignatura_Activa;
		
		private string _Asignatura_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAsignatura_IdChanging(int value);
    partial void OnAsignatura_IdChanged();
    partial void OnAsignatura_NombreChanging(string value);
    partial void OnAsignatura_NombreChanged();
    partial void OnAsignatura_Fecha_InicioChanging(System.DateTime value);
    partial void OnAsignatura_Fecha_InicioChanged();
    partial void OnAsignatura_Fecha_FinChanging(System.Nullable<System.DateTime> value);
    partial void OnAsignatura_Fecha_FinChanged();
    partial void OnAsignatura_ActivaChanging(bool value);
    partial void OnAsignatura_ActivaChanged();
    partial void OnAsignatura_ObservacionesChanging(string value);
    partial void OnAsignatura_ObservacionesChanged();
    #endregion
		
		public Asignaturas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Asignatura_Id
		{
			get
			{
				return this._Asignatura_Id;
			}
			set
			{
				if ((this._Asignatura_Id != value))
				{
					this.OnAsignatura_IdChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Id = value;
					this.SendPropertyChanged("Asignatura_Id");
					this.OnAsignatura_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Asignatura_Nombre
		{
			get
			{
				return this._Asignatura_Nombre;
			}
			set
			{
				if ((this._Asignatura_Nombre != value))
				{
					this.OnAsignatura_NombreChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Nombre = value;
					this.SendPropertyChanged("Asignatura_Nombre");
					this.OnAsignatura_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Fecha_Inicio", DbType="Date NOT NULL")]
		public System.DateTime Asignatura_Fecha_Inicio
		{
			get
			{
				return this._Asignatura_Fecha_Inicio;
			}
			set
			{
				if ((this._Asignatura_Fecha_Inicio != value))
				{
					this.OnAsignatura_Fecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Fecha_Inicio = value;
					this.SendPropertyChanged("Asignatura_Fecha_Inicio");
					this.OnAsignatura_Fecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Fecha_Fin", DbType="Date")]
		public System.Nullable<System.DateTime> Asignatura_Fecha_Fin
		{
			get
			{
				return this._Asignatura_Fecha_Fin;
			}
			set
			{
				if ((this._Asignatura_Fecha_Fin != value))
				{
					this.OnAsignatura_Fecha_FinChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Fecha_Fin = value;
					this.SendPropertyChanged("Asignatura_Fecha_Fin");
					this.OnAsignatura_Fecha_FinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Activa", DbType="Bit NOT NULL")]
		public bool Asignatura_Activa
		{
			get
			{
				return this._Asignatura_Activa;
			}
			set
			{
				if ((this._Asignatura_Activa != value))
				{
					this.OnAsignatura_ActivaChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Activa = value;
					this.SendPropertyChanged("Asignatura_Activa");
					this.OnAsignatura_ActivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Asignatura_Observaciones
		{
			get
			{
				return this._Asignatura_Observaciones;
			}
			set
			{
				if ((this._Asignatura_Observaciones != value))
				{
					this.OnAsignatura_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Observaciones = value;
					this.SendPropertyChanged("Asignatura_Observaciones");
					this.OnAsignatura_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
