<?xml version="1.0" encoding="utf-8"?><Database Name="Alexna" Class="alexnaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-BHUC62C\SQLEXPRESS;Initial Catalog=Alexna;Persist Security Info=True;User ID=alexna" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AlexnaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Festivos" Member="Festivos">
    <Type Name="Festivos">
      <Column Name="Festivo_Fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Festivo_Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="administrador" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="profesor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="alumno" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="mantenimiento" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>