<?xml version="1.0" encoding="utf-8"?><Database Name="Alexna" Class="alexnaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-BHUC62C\SQLEXPRESS;Initial Catalog=Alexna;Persist Security Info=True;User ID=alexna" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AlexnaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Festivos" Member="Festivos">
    <Type Name="Festivos">
      <Column Name="Festivo_Fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Festivo_Descripcion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="administrador" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="profesor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="alumno" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="mantenimiento" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cursos" Member="Cursos">
    <Type Name="Cursos">
      <Column Name="Curso_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Curso_Nombre" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="Curso_Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Curso_Fecha_Inicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Curso_Fecha_Fin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Curso_Observaciones" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Asignaturas" Member="Asignaturas">
    <Type Name="Asignaturas">
      <Column Name="Asignatura_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Asignatura_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Asignatura_Fecha_Inicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Asignatura_Fecha_Fin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Asignatura_Activa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Asignatura_Observaciones" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Vacaciones" Member="Vacaciones">
    <Type Name="Vacaciones">
      <Column Name="Vacacion_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Vacacion_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vacacion_Fecha_Inicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Vacacion_Fecha_Fin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Vacacion_Observaciones" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Personas" Member="Personas">
    <Type Name="Personas">
      <Column Name="Persona_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Persona_Identificacion_Legal" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Persona_Foto" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Persona_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Persona_Apellido_1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Persona_Apellido_2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Persona_Alias" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Persona_Sexo" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Persona_Fecha_Nacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Persona_Fecha_Muerte" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Persona_Observaciones" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>