#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexna.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Alexna")]
	public partial class alexnaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertFestivos(Festivos instance);
    partial void UpdateFestivos(Festivos instance);
    partial void DeleteFestivos(Festivos instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertCursos(Cursos instance);
    partial void UpdateCursos(Cursos instance);
    partial void DeleteCursos(Cursos instance);
    partial void InsertAsignaturas(Asignaturas instance);
    partial void UpdateAsignaturas(Asignaturas instance);
    partial void DeleteAsignaturas(Asignaturas instance);
    partial void InsertVacaciones(Vacaciones instance);
    partial void UpdateVacaciones(Vacaciones instance);
    partial void DeleteVacaciones(Vacaciones instance);
    partial void InsertPersonas(Personas instance);
    partial void UpdatePersonas(Personas instance);
    partial void DeletePersonas(Personas instance);
    partial void InsertPaises(Paises instance);
    partial void UpdatePaises(Paises instance);
    partial void DeletePaises(Paises instance);
    partial void InsertRegiones(Regiones instance);
    partial void UpdateRegiones(Regiones instance);
    partial void DeleteRegiones(Regiones instance);
    partial void InsertAulas(Aulas instance);
    partial void UpdateAulas(Aulas instance);
    partial void DeleteAulas(Aulas instance);
    #endregion
		
		public alexnaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AlexnaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alexnaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Festivos> Festivos
		{
			get
			{
				return this.GetTable<Festivos>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Cursos> Cursos
		{
			get
			{
				return this.GetTable<Cursos>();
			}
		}
		
		public System.Data.Linq.Table<Asignaturas> Asignaturas
		{
			get
			{
				return this.GetTable<Asignaturas>();
			}
		}
		
		public System.Data.Linq.Table<Vacaciones> Vacaciones
		{
			get
			{
				return this.GetTable<Vacaciones>();
			}
		}
		
		public System.Data.Linq.Table<Personas> Personas
		{
			get
			{
				return this.GetTable<Personas>();
			}
		}
		
		public System.Data.Linq.Table<Paises> Paises
		{
			get
			{
				return this.GetTable<Paises>();
			}
		}
		
		public System.Data.Linq.Table<Regiones> Regiones
		{
			get
			{
				return this.GetTable<Regiones>();
			}
		}
		
		public System.Data.Linq.Table<Aulas> Aulas
		{
			get
			{
				return this.GetTable<Aulas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Festivos")]
	public partial class Festivos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Festivo_Fecha;
		
		private string _Festivo_Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFestivo_FechaChanging(System.DateTime value);
    partial void OnFestivo_FechaChanged();
    partial void OnFestivo_DescripcionChanging(string value);
    partial void OnFestivo_DescripcionChanged();
    #endregion
		
		public Festivos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Festivo_Fecha", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Festivo_Fecha
		{
			get
			{
				return this._Festivo_Fecha;
			}
			set
			{
				if ((this._Festivo_Fecha != value))
				{
					this.OnFestivo_FechaChanging(value);
					this.SendPropertyChanging();
					this._Festivo_Fecha = value;
					this.SendPropertyChanged("Festivo_Fecha");
					this.OnFestivo_FechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Festivo_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Festivo_Descripcion
		{
			get
			{
				return this._Festivo_Descripcion;
			}
			set
			{
				if ((this._Festivo_Descripcion != value))
				{
					this.OnFestivo_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._Festivo_Descripcion = value;
					this.SendPropertyChanged("Festivo_Descripcion");
					this.OnFestivo_DescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _usuario;
		
		private string _password;
		
		private bool _administrador;
		
		private bool _profesor;
		
		private bool _alumno;
		
		private bool _mantenimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnadministradorChanging(bool value);
    partial void OnadministradorChanged();
    partial void OnprofesorChanging(bool value);
    partial void OnprofesorChanged();
    partial void OnalumnoChanging(bool value);
    partial void OnalumnoChanged();
    partial void OnmantenimientoChanging(bool value);
    partial void OnmantenimientoChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_administrador", DbType="Bit NOT NULL")]
		public bool administrador
		{
			get
			{
				return this._administrador;
			}
			set
			{
				if ((this._administrador != value))
				{
					this.OnadministradorChanging(value);
					this.SendPropertyChanging();
					this._administrador = value;
					this.SendPropertyChanged("administrador");
					this.OnadministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profesor", DbType="Bit NOT NULL")]
		public bool profesor
		{
			get
			{
				return this._profesor;
			}
			set
			{
				if ((this._profesor != value))
				{
					this.OnprofesorChanging(value);
					this.SendPropertyChanging();
					this._profesor = value;
					this.SendPropertyChanged("profesor");
					this.OnprofesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno", DbType="Bit NOT NULL")]
		public bool alumno
		{
			get
			{
				return this._alumno;
			}
			set
			{
				if ((this._alumno != value))
				{
					this.OnalumnoChanging(value);
					this.SendPropertyChanging();
					this._alumno = value;
					this.SendPropertyChanged("alumno");
					this.OnalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mantenimiento", DbType="Bit NOT NULL")]
		public bool mantenimiento
		{
			get
			{
				return this._mantenimiento;
			}
			set
			{
				if ((this._mantenimiento != value))
				{
					this.OnmantenimientoChanging(value);
					this.SendPropertyChanging();
					this._mantenimiento = value;
					this.SendPropertyChanged("mantenimiento");
					this.OnmantenimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cursos")]
	public partial class Cursos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Curso_Id;
		
		private string _Curso_Nombre;
		
		private bool _Curso_Activo;
		
		private System.DateTime _Curso_Fecha_Inicio;
		
		private System.DateTime _Curso_Fecha_Fin;
		
		private string _Curso_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCurso_IdChanging(int value);
    partial void OnCurso_IdChanged();
    partial void OnCurso_NombreChanging(string value);
    partial void OnCurso_NombreChanged();
    partial void OnCurso_ActivoChanging(bool value);
    partial void OnCurso_ActivoChanged();
    partial void OnCurso_Fecha_InicioChanging(System.DateTime value);
    partial void OnCurso_Fecha_InicioChanged();
    partial void OnCurso_Fecha_FinChanging(System.DateTime value);
    partial void OnCurso_Fecha_FinChanged();
    partial void OnCurso_ObservacionesChanging(string value);
    partial void OnCurso_ObservacionesChanged();
    #endregion
		
		public Cursos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Curso_Id
		{
			get
			{
				return this._Curso_Id;
			}
			set
			{
				if ((this._Curso_Id != value))
				{
					this.OnCurso_IdChanging(value);
					this.SendPropertyChanging();
					this._Curso_Id = value;
					this.SendPropertyChanged("Curso_Id");
					this.OnCurso_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Nombre", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string Curso_Nombre
		{
			get
			{
				return this._Curso_Nombre;
			}
			set
			{
				if ((this._Curso_Nombre != value))
				{
					this.OnCurso_NombreChanging(value);
					this.SendPropertyChanging();
					this._Curso_Nombre = value;
					this.SendPropertyChanged("Curso_Nombre");
					this.OnCurso_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Activo", DbType="Bit NOT NULL")]
		public bool Curso_Activo
		{
			get
			{
				return this._Curso_Activo;
			}
			set
			{
				if ((this._Curso_Activo != value))
				{
					this.OnCurso_ActivoChanging(value);
					this.SendPropertyChanging();
					this._Curso_Activo = value;
					this.SendPropertyChanged("Curso_Activo");
					this.OnCurso_ActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Fecha_Inicio", DbType="Date NOT NULL")]
		public System.DateTime Curso_Fecha_Inicio
		{
			get
			{
				return this._Curso_Fecha_Inicio;
			}
			set
			{
				if ((this._Curso_Fecha_Inicio != value))
				{
					this.OnCurso_Fecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Curso_Fecha_Inicio = value;
					this.SendPropertyChanged("Curso_Fecha_Inicio");
					this.OnCurso_Fecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Fecha_Fin", DbType="Date NOT NULL")]
		public System.DateTime Curso_Fecha_Fin
		{
			get
			{
				return this._Curso_Fecha_Fin;
			}
			set
			{
				if ((this._Curso_Fecha_Fin != value))
				{
					this.OnCurso_Fecha_FinChanging(value);
					this.SendPropertyChanging();
					this._Curso_Fecha_Fin = value;
					this.SendPropertyChanged("Curso_Fecha_Fin");
					this.OnCurso_Fecha_FinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Curso_Observaciones
		{
			get
			{
				return this._Curso_Observaciones;
			}
			set
			{
				if ((this._Curso_Observaciones != value))
				{
					this.OnCurso_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Curso_Observaciones = value;
					this.SendPropertyChanged("Curso_Observaciones");
					this.OnCurso_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asignaturas")]
	public partial class Asignaturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Asignatura_Id;
		
		private string _Asignatura_Nombre;
		
		private System.DateTime _Asignatura_Fecha_Inicio;
		
		private System.Nullable<System.DateTime> _Asignatura_Fecha_Fin;
		
		private bool _Asignatura_Activa;
		
		private string _Asignatura_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAsignatura_IdChanging(int value);
    partial void OnAsignatura_IdChanged();
    partial void OnAsignatura_NombreChanging(string value);
    partial void OnAsignatura_NombreChanged();
    partial void OnAsignatura_Fecha_InicioChanging(System.DateTime value);
    partial void OnAsignatura_Fecha_InicioChanged();
    partial void OnAsignatura_Fecha_FinChanging(System.Nullable<System.DateTime> value);
    partial void OnAsignatura_Fecha_FinChanged();
    partial void OnAsignatura_ActivaChanging(bool value);
    partial void OnAsignatura_ActivaChanged();
    partial void OnAsignatura_ObservacionesChanging(string value);
    partial void OnAsignatura_ObservacionesChanged();
    #endregion
		
		public Asignaturas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Asignatura_Id
		{
			get
			{
				return this._Asignatura_Id;
			}
			set
			{
				if ((this._Asignatura_Id != value))
				{
					this.OnAsignatura_IdChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Id = value;
					this.SendPropertyChanged("Asignatura_Id");
					this.OnAsignatura_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Asignatura_Nombre
		{
			get
			{
				return this._Asignatura_Nombre;
			}
			set
			{
				if ((this._Asignatura_Nombre != value))
				{
					this.OnAsignatura_NombreChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Nombre = value;
					this.SendPropertyChanged("Asignatura_Nombre");
					this.OnAsignatura_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Fecha_Inicio", DbType="Date NOT NULL")]
		public System.DateTime Asignatura_Fecha_Inicio
		{
			get
			{
				return this._Asignatura_Fecha_Inicio;
			}
			set
			{
				if ((this._Asignatura_Fecha_Inicio != value))
				{
					this.OnAsignatura_Fecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Fecha_Inicio = value;
					this.SendPropertyChanged("Asignatura_Fecha_Inicio");
					this.OnAsignatura_Fecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Fecha_Fin", DbType="Date")]
		public System.Nullable<System.DateTime> Asignatura_Fecha_Fin
		{
			get
			{
				return this._Asignatura_Fecha_Fin;
			}
			set
			{
				if ((this._Asignatura_Fecha_Fin != value))
				{
					this.OnAsignatura_Fecha_FinChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Fecha_Fin = value;
					this.SendPropertyChanged("Asignatura_Fecha_Fin");
					this.OnAsignatura_Fecha_FinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Activa", DbType="Bit NOT NULL")]
		public bool Asignatura_Activa
		{
			get
			{
				return this._Asignatura_Activa;
			}
			set
			{
				if ((this._Asignatura_Activa != value))
				{
					this.OnAsignatura_ActivaChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Activa = value;
					this.SendPropertyChanged("Asignatura_Activa");
					this.OnAsignatura_ActivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignatura_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Asignatura_Observaciones
		{
			get
			{
				return this._Asignatura_Observaciones;
			}
			set
			{
				if ((this._Asignatura_Observaciones != value))
				{
					this.OnAsignatura_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Asignatura_Observaciones = value;
					this.SendPropertyChanged("Asignatura_Observaciones");
					this.OnAsignatura_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vacaciones")]
	public partial class Vacaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Vacacion_Id;
		
		private string _Vacacion_Nombre;
		
		private System.DateTime _Vacacion_Fecha_Inicio;
		
		private System.DateTime _Vacacion_Fecha_Fin;
		
		private string _Vacacion_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVacacion_IdChanging(int value);
    partial void OnVacacion_IdChanged();
    partial void OnVacacion_NombreChanging(string value);
    partial void OnVacacion_NombreChanged();
    partial void OnVacacion_Fecha_InicioChanging(System.DateTime value);
    partial void OnVacacion_Fecha_InicioChanged();
    partial void OnVacacion_Fecha_FinChanging(System.DateTime value);
    partial void OnVacacion_Fecha_FinChanged();
    partial void OnVacacion_ObservacionesChanging(string value);
    partial void OnVacacion_ObservacionesChanged();
    #endregion
		
		public Vacaciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacacion_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Vacacion_Id
		{
			get
			{
				return this._Vacacion_Id;
			}
			set
			{
				if ((this._Vacacion_Id != value))
				{
					this.OnVacacion_IdChanging(value);
					this.SendPropertyChanging();
					this._Vacacion_Id = value;
					this.SendPropertyChanged("Vacacion_Id");
					this.OnVacacion_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacacion_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Vacacion_Nombre
		{
			get
			{
				return this._Vacacion_Nombre;
			}
			set
			{
				if ((this._Vacacion_Nombre != value))
				{
					this.OnVacacion_NombreChanging(value);
					this.SendPropertyChanging();
					this._Vacacion_Nombre = value;
					this.SendPropertyChanged("Vacacion_Nombre");
					this.OnVacacion_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacacion_Fecha_Inicio", DbType="Date NOT NULL")]
		public System.DateTime Vacacion_Fecha_Inicio
		{
			get
			{
				return this._Vacacion_Fecha_Inicio;
			}
			set
			{
				if ((this._Vacacion_Fecha_Inicio != value))
				{
					this.OnVacacion_Fecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Vacacion_Fecha_Inicio = value;
					this.SendPropertyChanged("Vacacion_Fecha_Inicio");
					this.OnVacacion_Fecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacacion_Fecha_Fin", DbType="Date NOT NULL")]
		public System.DateTime Vacacion_Fecha_Fin
		{
			get
			{
				return this._Vacacion_Fecha_Fin;
			}
			set
			{
				if ((this._Vacacion_Fecha_Fin != value))
				{
					this.OnVacacion_Fecha_FinChanging(value);
					this.SendPropertyChanging();
					this._Vacacion_Fecha_Fin = value;
					this.SendPropertyChanged("Vacacion_Fecha_Fin");
					this.OnVacacion_Fecha_FinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vacacion_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Vacacion_Observaciones
		{
			get
			{
				return this._Vacacion_Observaciones;
			}
			set
			{
				if ((this._Vacacion_Observaciones != value))
				{
					this.OnVacacion_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Vacacion_Observaciones = value;
					this.SendPropertyChanged("Vacacion_Observaciones");
					this.OnVacacion_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personas")]
	public partial class Personas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Persona_Id;
		
		private string _Persona_Identificacion_Legal;
		
		private string _Persona_Foto;
		
		private string _Persona_Nombre;
		
		private string _Persona_Apellido_1;
		
		private string _Persona_Apellido_2;
		
		private string _Persona_Alias;
		
		private string _Persona_Sexo;
		
		private System.Nullable<System.DateTime> _Persona_Fecha_Nacimiento;
		
		private System.Nullable<System.DateTime> _Persona_Fecha_Muerte;
		
		private string _Persona_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersona_IdChanging(int value);
    partial void OnPersona_IdChanged();
    partial void OnPersona_Identificacion_LegalChanging(string value);
    partial void OnPersona_Identificacion_LegalChanged();
    partial void OnPersona_FotoChanging(string value);
    partial void OnPersona_FotoChanged();
    partial void OnPersona_NombreChanging(string value);
    partial void OnPersona_NombreChanged();
    partial void OnPersona_Apellido_1Changing(string value);
    partial void OnPersona_Apellido_1Changed();
    partial void OnPersona_Apellido_2Changing(string value);
    partial void OnPersona_Apellido_2Changed();
    partial void OnPersona_AliasChanging(string value);
    partial void OnPersona_AliasChanged();
    partial void OnPersona_SexoChanging(string value);
    partial void OnPersona_SexoChanged();
    partial void OnPersona_Fecha_NacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnPersona_Fecha_NacimientoChanged();
    partial void OnPersona_Fecha_MuerteChanging(System.Nullable<System.DateTime> value);
    partial void OnPersona_Fecha_MuerteChanged();
    partial void OnPersona_ObservacionesChanging(string value);
    partial void OnPersona_ObservacionesChanged();
    #endregion
		
		public Personas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Persona_Id
		{
			get
			{
				return this._Persona_Id;
			}
			set
			{
				if ((this._Persona_Id != value))
				{
					this.OnPersona_IdChanging(value);
					this.SendPropertyChanging();
					this._Persona_Id = value;
					this.SendPropertyChanged("Persona_Id");
					this.OnPersona_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Identificacion_Legal", DbType="NVarChar(50)")]
		public string Persona_Identificacion_Legal
		{
			get
			{
				return this._Persona_Identificacion_Legal;
			}
			set
			{
				if ((this._Persona_Identificacion_Legal != value))
				{
					this.OnPersona_Identificacion_LegalChanging(value);
					this.SendPropertyChanging();
					this._Persona_Identificacion_Legal = value;
					this.SendPropertyChanged("Persona_Identificacion_Legal");
					this.OnPersona_Identificacion_LegalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Foto", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Persona_Foto
		{
			get
			{
				return this._Persona_Foto;
			}
			set
			{
				if ((this._Persona_Foto != value))
				{
					this.OnPersona_FotoChanging(value);
					this.SendPropertyChanging();
					this._Persona_Foto = value;
					this.SendPropertyChanged("Persona_Foto");
					this.OnPersona_FotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Persona_Nombre
		{
			get
			{
				return this._Persona_Nombre;
			}
			set
			{
				if ((this._Persona_Nombre != value))
				{
					this.OnPersona_NombreChanging(value);
					this.SendPropertyChanging();
					this._Persona_Nombre = value;
					this.SendPropertyChanged("Persona_Nombre");
					this.OnPersona_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Apellido_1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Persona_Apellido_1
		{
			get
			{
				return this._Persona_Apellido_1;
			}
			set
			{
				if ((this._Persona_Apellido_1 != value))
				{
					this.OnPersona_Apellido_1Changing(value);
					this.SendPropertyChanging();
					this._Persona_Apellido_1 = value;
					this.SendPropertyChanged("Persona_Apellido_1");
					this.OnPersona_Apellido_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Apellido_2", DbType="NVarChar(50)")]
		public string Persona_Apellido_2
		{
			get
			{
				return this._Persona_Apellido_2;
			}
			set
			{
				if ((this._Persona_Apellido_2 != value))
				{
					this.OnPersona_Apellido_2Changing(value);
					this.SendPropertyChanging();
					this._Persona_Apellido_2 = value;
					this.SendPropertyChanged("Persona_Apellido_2");
					this.OnPersona_Apellido_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Alias", DbType="NVarChar(50)")]
		public string Persona_Alias
		{
			get
			{
				return this._Persona_Alias;
			}
			set
			{
				if ((this._Persona_Alias != value))
				{
					this.OnPersona_AliasChanging(value);
					this.SendPropertyChanging();
					this._Persona_Alias = value;
					this.SendPropertyChanged("Persona_Alias");
					this.OnPersona_AliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Sexo", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string Persona_Sexo
		{
			get
			{
				return this._Persona_Sexo;
			}
			set
			{
				if ((this._Persona_Sexo != value))
				{
					this.OnPersona_SexoChanging(value);
					this.SendPropertyChanging();
					this._Persona_Sexo = value;
					this.SendPropertyChanged("Persona_Sexo");
					this.OnPersona_SexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Fecha_Nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> Persona_Fecha_Nacimiento
		{
			get
			{
				return this._Persona_Fecha_Nacimiento;
			}
			set
			{
				if ((this._Persona_Fecha_Nacimiento != value))
				{
					this.OnPersona_Fecha_NacimientoChanging(value);
					this.SendPropertyChanging();
					this._Persona_Fecha_Nacimiento = value;
					this.SendPropertyChanged("Persona_Fecha_Nacimiento");
					this.OnPersona_Fecha_NacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Fecha_Muerte", DbType="Date")]
		public System.Nullable<System.DateTime> Persona_Fecha_Muerte
		{
			get
			{
				return this._Persona_Fecha_Muerte;
			}
			set
			{
				if ((this._Persona_Fecha_Muerte != value))
				{
					this.OnPersona_Fecha_MuerteChanging(value);
					this.SendPropertyChanging();
					this._Persona_Fecha_Muerte = value;
					this.SendPropertyChanged("Persona_Fecha_Muerte");
					this.OnPersona_Fecha_MuerteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Persona_Observaciones
		{
			get
			{
				return this._Persona_Observaciones;
			}
			set
			{
				if ((this._Persona_Observaciones != value))
				{
					this.OnPersona_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Persona_Observaciones = value;
					this.SendPropertyChanged("Persona_Observaciones");
					this.OnPersona_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paises")]
	public partial class Paises : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pais_Id;
		
		private string _Pais_Nombre;
		
		private string _Pais_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPais_IdChanging(int value);
    partial void OnPais_IdChanged();
    partial void OnPais_NombreChanging(string value);
    partial void OnPais_NombreChanged();
    partial void OnPais_ObservacionesChanging(string value);
    partial void OnPais_ObservacionesChanged();
    #endregion
		
		public Paises()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pais_Id
		{
			get
			{
				return this._Pais_Id;
			}
			set
			{
				if ((this._Pais_Id != value))
				{
					this.OnPais_IdChanging(value);
					this.SendPropertyChanging();
					this._Pais_Id = value;
					this.SendPropertyChanged("Pais_Id");
					this.OnPais_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pais_Nombre
		{
			get
			{
				return this._Pais_Nombre;
			}
			set
			{
				if ((this._Pais_Nombre != value))
				{
					this.OnPais_NombreChanging(value);
					this.SendPropertyChanging();
					this._Pais_Nombre = value;
					this.SendPropertyChanged("Pais_Nombre");
					this.OnPais_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Pais_Observaciones
		{
			get
			{
				return this._Pais_Observaciones;
			}
			set
			{
				if ((this._Pais_Observaciones != value))
				{
					this.OnPais_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Pais_Observaciones = value;
					this.SendPropertyChanged("Pais_Observaciones");
					this.OnPais_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Regiones")]
	public partial class Regiones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Region_Id;
		
		private int _Pais_Id;
		
		private string _Region_Nombre;
		
		private string _Region_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegion_IdChanging(int value);
    partial void OnRegion_IdChanged();
    partial void OnPais_IdChanging(int value);
    partial void OnPais_IdChanged();
    partial void OnRegion_NombreChanging(string value);
    partial void OnRegion_NombreChanged();
    partial void OnRegion_ObservacionesChanging(string value);
    partial void OnRegion_ObservacionesChanged();
    #endregion
		
		public Regiones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Region_Id
		{
			get
			{
				return this._Region_Id;
			}
			set
			{
				if ((this._Region_Id != value))
				{
					this.OnRegion_IdChanging(value);
					this.SendPropertyChanging();
					this._Region_Id = value;
					this.SendPropertyChanged("Region_Id");
					this.OnRegion_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais_Id", DbType="Int NOT NULL")]
		public int Pais_Id
		{
			get
			{
				return this._Pais_Id;
			}
			set
			{
				if ((this._Pais_Id != value))
				{
					this.OnPais_IdChanging(value);
					this.SendPropertyChanging();
					this._Pais_Id = value;
					this.SendPropertyChanged("Pais_Id");
					this.OnPais_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Region_Nombre
		{
			get
			{
				return this._Region_Nombre;
			}
			set
			{
				if ((this._Region_Nombre != value))
				{
					this.OnRegion_NombreChanging(value);
					this.SendPropertyChanging();
					this._Region_Nombre = value;
					this.SendPropertyChanged("Region_Nombre");
					this.OnRegion_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Region_Observaciones
		{
			get
			{
				return this._Region_Observaciones;
			}
			set
			{
				if ((this._Region_Observaciones != value))
				{
					this.OnRegion_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Region_Observaciones = value;
					this.SendPropertyChanged("Region_Observaciones");
					this.OnRegion_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aulas")]
	public partial class Aulas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Aula_Id;
		
		private string _Aula_Nombre;
		
		private bool _Aula_Activa;
		
		private string _Aula_Observaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAula_IdChanging(int value);
    partial void OnAula_IdChanged();
    partial void OnAula_NombreChanging(string value);
    partial void OnAula_NombreChanged();
    partial void OnAula_ActivaChanging(bool value);
    partial void OnAula_ActivaChanged();
    partial void OnAula_ObservacionesChanging(string value);
    partial void OnAula_ObservacionesChanged();
    #endregion
		
		public Aulas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aula_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Aula_Id
		{
			get
			{
				return this._Aula_Id;
			}
			set
			{
				if ((this._Aula_Id != value))
				{
					this.OnAula_IdChanging(value);
					this.SendPropertyChanging();
					this._Aula_Id = value;
					this.SendPropertyChanged("Aula_Id");
					this.OnAula_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aula_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Aula_Nombre
		{
			get
			{
				return this._Aula_Nombre;
			}
			set
			{
				if ((this._Aula_Nombre != value))
				{
					this.OnAula_NombreChanging(value);
					this.SendPropertyChanging();
					this._Aula_Nombre = value;
					this.SendPropertyChanged("Aula_Nombre");
					this.OnAula_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aula_Activa", DbType="Bit NOT NULL")]
		public bool Aula_Activa
		{
			get
			{
				return this._Aula_Activa;
			}
			set
			{
				if ((this._Aula_Activa != value))
				{
					this.OnAula_ActivaChanging(value);
					this.SendPropertyChanging();
					this._Aula_Activa = value;
					this.SendPropertyChanged("Aula_Activa");
					this.OnAula_ActivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aula_Observaciones", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Aula_Observaciones
		{
			get
			{
				return this._Aula_Observaciones;
			}
			set
			{
				if ((this._Aula_Observaciones != value))
				{
					this.OnAula_ObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Aula_Observaciones = value;
					this.SendPropertyChanged("Aula_Observaciones");
					this.OnAula_ObservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
